services:
    # Managers
    bluetea_export.export_manager:
        class: %bluetea_export.export_manager.class%
        arguments:
            - @bluetea_export.entity_manager
            - %bluetea_export.model.export.class%

    bluetea_export.entity_manager:
        class: Doctrine\ORM\EntityManager
        factory_service: doctrine
        factory_method: getManager

    # Export services
    bluetea_export.factory.csv:
        class: Bluetea\ExportBundle\Factory\CSVFactory

    bluetea_export.csv:
        class: Bluetea\ExportBundle\Services\Export
        arguments:
            - @bluetea_export.factory.csv
            - @event_dispatcher
            - @bluetea_export.export_manager

    bluetea_export.chain:
        class: %bluetea_export.chain.class%

    acme_export.your_export_type:
        class: Bluetea\ExportBundle\Export\Type\ExampleExportType
        arguments:
            - @service_container
            - @bluetea_export.entity_manager
        tags:
            - { name: bluetea_export.export_type, description: 'test' }